import { useMemo, useState } from "react";
import { ArrowLeft, ChevronDown, ChevronRight, Search, X } from "lucide-react";
import type { Intervention } from "../types";

const categories = [
  { id: "cat-ram", label: "Mémoire / RAM", kind: "hardware" }, { id: "cat-storage", label: "Extension de stockage", kind: "hardware" },
  { id: "cat-blackscreen", label: "Écran noir", kind: "hardware" }, { id: "cat-psu", label: "Alimentation", kind: "hardware" },
  { id: "cat-os", label: "Système d’exploitation", kind: "software" }, { id: "cat-antivirus", label: "Antivirus", kind: "software" },
];
const classes = [{ id: "cls-error", label: "Erreur" }, { id: "cls-install", label: "Installation" }, { id: "cls-upgrade", label: "Mise à niveau" }, { id: "cls-replacement", label: "Remplacement" }];

export default function InterventionsHistoryPage({ interventions, onBack, onOpenIntervention }: { interventions: Intervention[]; onBack?: () => void; onOpenIntervention?: (id: string) => void }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [changeClass, setChangeClass] = useState("all"); const [expanded, setExpanded] = useState<string | null>(null); const [page, setPage] = useState(1);
  const filtered = useMemo(() => interventions.filter((item) => (!query.trim() || `${item.bureau} ${item.equipmentId}`.toLowerCase().includes(query.trim().toLowerCase())) && (category === "all" || item.categoryId === category) && (changeClass === "all" || item.classId === changeClass)), [interventions, query, category, changeClass]);
  const pageSize = 6; const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const currentPage = Math.min(page, totalPages); const shown = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize); const categoryMap = new Map(categories.map((item) => [item.id, item])); const classMap = new Map(classes.map((item) => [item.id, item.label]));
  const reset = () => { setQuery(""); setCategory("all"); setChangeClass("all"); setPage(1); };
  return <div className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><button type="button" onClick={onBack} className="inline-flex items-center gap-1.5 rounded-md text-sm font-medium text-slate-500 hover:text-slate-900"><ArrowLeft className="h-4 w-4" />Retour au tableau de bord</button><div className="mt-4"><h1 className="text-2xl font-semibold tracking-tight">Historique des interventions</h1><p className="mt-1 text-sm text-slate-500">{filtered.length} intervention{filtered.length > 1 ? "s" : ""} au total</p></div>
    <div className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end gap-3"><label className="flex min-w-[220px] flex-1 flex-col gap-1 text-xs font-medium text-slate-500">Bureau ou équipement<div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="search" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="B-104, PC-DZ-01142…" className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pl-9 pr-3 text-sm focus:border-orange-500 focus:bg-white focus:outline-none" /></div></label><label className="flex flex-col gap-1 text-xs font-medium text-slate-500">Type de changement<select value={category} onChange={(event) => { setCategory(event.target.value); setPage(1); }} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="all">Tous</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="flex flex-col gap-1 text-xs font-medium text-slate-500">Classe<select value={changeClass} onChange={(event) => { setChangeClass(event.target.value); setPage(1); }} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="all">Tous</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>{(query || category !== "all" || changeClass !== "all") && <button type="button" onClick={reset} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-500"><X className="h-3.5 w-3.5" />Réinitialiser</button>}</div></div>
    <div className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><ul className="divide-y divide-slate-100">{shown.map((item) => { const cat = categoryMap.get(item.categoryId); const open = expanded === item.id; return <li key={item.id}><button type="button" onClick={() => setExpanded(open ? null : item.id)} className="flex w-full items-center justify-between gap-4 px-6 py-4 text-left hover:bg-slate-50"><span className="flex min-w-0 flex-1 items-center gap-4"><span className="w-16 shrink-0 font-mono text-sm">{item.bureau}</span><span className="w-28 shrink-0 truncate font-mono text-sm text-slate-600">{item.equipmentId}</span><span className={`rounded-md px-2 py-1 text-xs font-semibold ${cat?.kind === "hardware" ? "bg-orange-50 text-orange-600" : "bg-blue-50 text-blue-600"}`}>{cat?.kind === "hardware" ? "[H] Matériel" : "[S] Logiciel"}</span><span className="truncate text-sm text-slate-700">{cat?.label} <span className="text-slate-400">· {classMap.get(item.classId)}</span></span></span><span className="flex shrink-0 items-center gap-3 text-sm text-slate-500">{item.timestamp}<ChevronDown className={`h-4 w-4 ${open ? "rotate-180" : ""}`} /></span></button>{open && <div className="border-t border-slate-100 bg-slate-50 px-6 py-4"><p className="text-sm text-slate-700">{item.description}</p><p className="mt-3 text-xs text-slate-500">Technicien : <span className="font-medium text-slate-700">{item.technician}</span></p><button type="button" onClick={() => onOpenIntervention?.(item.id)} className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-orange-600">Voir la fiche complète<ChevronRight className="h-4 w-4" /></button></div>}</li>; })}</ul>{shown.length === 0 && <p className="px-6 py-10 text-center text-sm text-slate-500">Aucune intervention ne correspond à ces filtres.</p>}{totalPages > 1 && <div className="flex items-center justify-between border-t border-slate-200 px-6 py-3"><span className="text-xs text-slate-500">Page {currentPage} sur {totalPages}</span><span className="flex gap-2"><button type="button" disabled={currentPage === 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border px-3 py-1.5 text-xs disabled:opacity-40">Précédent</button><button type="button" disabled={currentPage === totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border px-3 py-1.5 text-xs disabled:opacity-40">Suivant</button></span></div>}</div>
  </div></div>;
}
